# Utilisation d'une image légère avec Apache déjà configuré
FROM php:8.2-apache

# On expose le port 80 (port par défaut d'Apache)
EXPOSE 80

# On copie notre fichier index.php dans le dossier public du serveur
COPY index.php /var/www/html/